In [1]:
import pandas as pd
df=pd.read_excel('/content/Sample - Superstore.xlsx')

In [2]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
df.Sales.max()

22638.48

In [4]:
df.Sales.min()

0.44399999999999995

In [10]:
s=df.Sales.count()

In [11]:
s1=df.Sales.sum()

In [12]:
avg=s1/s
print(avg)

229.85800083049833

In [15]:
df.groupby('Quantity').count()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Discount,Profit
Quantity,,,,,,,,,,,,,,,,,,,,
1,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899
2,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402
3,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409
4,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191
5,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230
6,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572
7,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606
8,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257
9,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258
10,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57
11,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34
12,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23
13,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27
14,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29

In [16]:
df.groupby('Quantity').max()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Discount,Profit
Quantity,,,,,,,,,,,,,,,,,,,,
1,9988,US-2017-167920,2017-12-29,2018-01-03,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Yonkers,Wisconsin,99301,West,TEC-PH-10004959,Technology,Tables,iOttie HLCRIO102 Car Mount,1270.990,0.8,635.4950
2,9994,US-2017-169551,2017-12-30,2018-01-05,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,York,Wisconsin,99301,West,TEC-PH-10004977,Technology,Tables,netTALK DUO VoIP Telephone Service,4799.984,0.8,1995.9900
3,9990,US-2017-169551,2017-12-30,2018-01-04,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,York,Wisconsin,99207,West,TEC-PH-10004977,Technology,Tables,netTALK DUO VoIP Telephone Service,10499.970,0.8,5039.9856
4,9993,US-2017-168802,2017-12-30,2018-01-04,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,Yuma,Wyoming,98661,West,TEC-PH-10004977,Technology,Tables,netTALK DUO VoIP Telephone Service,13999.960,0.8,6719.9808
5,9989,US-2017-169502,2017-12-29,2018-01-02,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,Yuma,Wisconsin,99301,West,TEC-PH-10004977,Technology,Tables,invisibleSHIELD by ZAGG Smudge-Free Screen Pro...,17499.950,0.8,8399.9760
6,9948,US-2017-167402,2017-12-28,2017-12-31,Standard Class,YS-21880,Yana Sorensen,Home Office,United States,Yuma,Wisconsin,99301,West,TEC-PH-10004922,Technology,Tables,iOttie HLCRIO102 Car Mount,22638.480,0.8,1453.1238
7,9983,US-2017-165344,2017-12-30,2018-01-04,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Yuma,Wisconsin,99207,West,TEC-PH-10004977,Technology,Tables,Zebra GX420t Direct Thermal/Thermal Transfer P...,9099.930,0.8,2400.9657
8,9949,US-2017-158526,2017-12-29,2018-01-05,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Yonkers,Wisconsin,99301,West,TEC-PH-10004531,Technology,Tables,Zipper Ring Binder Pockets,8159.952,0.8,1459.2000
9,9943,US-2017-166688,2017-12-25,2018-01-01,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Wilmington,Wisconsin,99207,West,TEC-PH-10004667,Technology,Tables,netTALK DUO VoIP Telephone Service,5399.910,0.8,2591.9568
10,9985,US-2017-165344,2017-12-04,2017-12-09,Standard Class,VT-21700,Valerie Takahito,Home Office,United States,Tucson,Washington,98226,West,TEC-PH-10004614,Technology,Tables,iKross Bluetooth Portable Keyboard + Cell Phon...,4007.840,0.8,394.2680
11,9896,US-2017-142188,2017-11-28,2017-12-02,Standard Class,TT-21460,Tonja Turnell,Home Office,United States,Vacaville,Wisconsin,98115,West,TEC-PH-10002834,Technology,Storage,Xerox 232,2888.127,0.7,767.2005
12,8871,US-2017-110576,2017-12-01,2017-12-06,Standard Class,XP-21865,Xylona Preis,Home Office,United States,Tulsa,Washington,98270,West,TEC-PH-10002496,Technology,Tables,"Wirebound Message Books, Four 2 3/4 x 5 White ...",3610.848,0.4,561.5640
13,9883,US-2017-147669,2017-12-25,2017-12-30,Standard Class,VP-21760,Victoria Pisteka,Home Office,United States,Woodstock,Washington,98103,West,TEC-PH-10004833,Technology,Tables,Xerox 1952,9892.740,0.8,4946.3700
14,9980,US-2017-155425,2017-12-14,2017-12-18,Standard Class,TG-21640,Trudy Glocke,Home Office,United States,Tucson,Washington,98103,West,TEC-PH-10001557,Technology,Storage,Xerox 1964,1819.860,0.8,510.6360

In [17]:
df.groupby('Quantity').min()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Discount,Profit
Quantity,,,,,,,,,,,,,,,,,,,,
1,53,CA-2014-100328,2014-01-06,2014-01-10,First Class,AA-10315,Aaron Bergman,Consumer,United States,Albuquerque,Alabama,1453,Central,FUR-BO-10000362,Furniture,Accessories,#10 Self-Seal White Envelopes,0.444,0.0,-170.8038
2,1,CA-2014-100363,2014-01-03,2014-01-07,First Class,AA-10315,Aaron Bergman,Consumer,United States,Abilene,Alabama,1040,Central,FUR-BO-10000330,Furniture,Accessories,"""While you Were Out"" Message Book, One Form pe...",0.984,0.0,-2639.9912
3,2,CA-2014-100006,2014-01-04,2014-01-07,First Class,AA-10315,Aaron Bergman,Consumer,United States,Aberdeen,Alabama,1453,Central,FUR-BO-10000362,Furniture,Accessories,"""While you Were Out"" Message Book, One Form pe...",1.080,0.0,-1143.8910
4,7,CA-2014-100762,2014-01-06,2014-01-10,First Class,AA-10480,Aaron Hawkins,Consumer,United States,Akron,Alabama,1453,Central,FUR-BO-10000330,Furniture,Accessories,"#10 Gummed Flap White Envelopes, 100/Box",1.344,0.0,-3839.9904
5,4,CA-2014-100860,2014-01-13,2014-01-17,First Class,AA-10375,Aaron Smayling,Consumer,United States,Akron,Alabama,1453,Central,FUR-BO-10001337,Furniture,Accessories,"#10 White Business Envelopes,4 1/8 x 9 1/2",1.680,0.0,-6599.9780
6,8,CA-2014-100090,2014-01-13,2014-01-15,First Class,AA-10375,Aaron Hawkins,Consumer,United States,Akron,Alabama,1841,Central,FUR-BO-10000362,Furniture,Accessories,#10 Self-Seal White Envelopes,4.488,0.0,-2287.7820
7,6,CA-2014-101392,2014-01-07,2014-01-12,First Class,AA-10315,Aaron Hawkins,Consumer,United States,Albuquerque,Alabama,1841,Central,FUR-BO-10000468,Furniture,Accessories,"#10 White Business Envelopes,4 1/8 x 9 1/2",2.772,0.0,-1665.0522
8,68,CA-2014-104780,2014-01-26,2014-01-31,First Class,AA-10480,Aaron Hawkins,Consumer,United States,Albuquerque,Alabama,2920,Central,FUR-BO-10002213,Furniture,Accessories,"#10 White Business Envelopes,4 1/8 x 9 1/2",5.728,0.0,-3701.8928
9,11,CA-2014-102673,2014-01-06,2014-01-10,First Class,AC-10450,Aaron Hawkins,Consumer,United States,Anaheim,Alabama,2149,Central,FUR-BO-10000112,Furniture,Accessories,"#10-4 1/8"" x 9 1/2"" Premium Diagonal Seam Enve...",3.240,0.0,-950.4000
10,330,CA-2014-111871,2014-01-19,2014-01-20,First Class,AB-10060,Adam Bellavance,Consumer,United States,Arlington,Arizona,1841,Central,FUR-BO-10002213,Furniture,Accessories,12-1/2 Diameter Round Wall Clock,3.960,0.0,-407.9760
11,148,CA-2014-115049,2014-04-19,2014-04-23,First Class,AC-10450,Aaron Smayling,Consumer,United States,Arlington,California,6824,Central,FUR-CH-10002073,Furniture,Accessories,Advantus Rolling Drawer Organizers,31.504,0.0,-52.5481
12,344,CA-2014-102673,2014-03-14,2014-03-19,First Class,AG-10330,Alex Grayson,Consumer,United States,Arlington,California,10035,Central,FUR-BO-10001608,Furniture,Accessories,"Acco PRESSTEX Data Binder with Storage Hooks, ...",35.760,0.0,-619.5960
13,252,CA-2014-101364,2014-01-26,2014-01-31,First Class,AB-10105,Adrian Barton,Consumer,United States,Alexandria,California,4401,Central,FUR-BO-10001972,Furniture,Accessories,Avery 485,13.468,0.0,-1862.3124
14,114,CA-2014-115259,2014-02-17,2014-02-24,First Class,AB-10600,Alejandro Grove,Consumer,United States,Alexandria,Alabama,10011,Central,FUR-CH-10000513,Furniture,Accessories,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",13.748,0.0,-135.7650

In [22]:
df.groupby('Ship Mode').count()

,Row ID,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Ship Mode,,,,,,,,,,,,,,,,,,,,
First Class,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538
Same Day,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543
Second Class,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945
Standard Class,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968

In [23]:
df.groupby('State').count()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
State,,,,,,,,,,,,,,,,,,,,
Alabama,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61
Arizona,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224
Arkansas,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60
California,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001
Colorado,182,182,182,182,182,182,182,182,182,182,182,182,182,182,182,182,182,182,182,182
Connecticut,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82
Delaware,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96
District of Columbia,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Florida,383,383,383,383,383,383,383,383,383,383,383,383,383,383,383,383,383,383,383,383
Georgia,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184
Idaho,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
Illinois,492,492,492,492,492,492,492,492,492,492,492,492,492,492,492,492,492,492,492,492
Indiana,149,149,149,149,149,149,149,149,149,149,149,149,149,149,149,149,149,149,149,149
Iowa,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
Kansas,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
Kentucky,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139
Louisiana,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42
Maine,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Maryland,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105
Massachusetts,135,135,135,135,135,135,135,135,135,135,135,135,135,135,135,135,135,135,135,135
Michigan,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255
Minnesota,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89
Mississippi,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53
Missouri,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66
Montana,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
Nebraska,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38
Nevada,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39
New Hampshire,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27
New Jersey,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130
New Mexico,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37
New York,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128,1128
North Carolina,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249
North Dakota,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Ohio,469,469,469,469,469,469,469,469,469,469,469,469,469,469,469,469,469,469,469,469
Oklahoma,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66
Oregon,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124
Pennsylvania,587,587,587,587,587,587,587,587,587,587,587,587,587,587,587,587,587,587,587,587
Rhode Island,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56
South Carolina,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42
South Dakota,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Tennessee,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183
Texas,985,985,985,985,985,985,985,985,985,985,985,985,985,985,985,985,985,985,985,985
Utah,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53
Vermont,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
Virginia,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224
Washington,506,506,506,506,506,506,506,506,506,506,506,506,506,506,506,506,506,506,506,506
West Virginia,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Wisconsin,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110
Wyoming,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [27]:
df.groupby('State').Sales.mean()

State
Alabama                  319.846557
Arizona                  157.508933
Arkansas                 194.635500
California               228.729451
Colorado                 176.418231
Connecticut              163.223866
Delaware                 285.948635
District of Columbia     286.502000
Florida                  233.612815
Georgia                  266.825217
Idaho                    208.689810
Illinois                 162.939230
Indiana                  359.431946
Iowa                     152.658667
Kansas                   121.429583
Kentucky                 263.250000
Louisiana                219.453095
Maine                    158.816250
Maryland                 225.766886
Massachusetts            212.106919
Michigan                 299.096525
Minnesota                335.541011
Mississippi              203.232830
Missouri                 336.441667
Montana                  372.623467
Nebraska                 196.445526
Nevada                   428.951333
New Hampshire            270.093481
New Jersey               275.110092
New Mexico               129.284378
New York                 275.599531
North Carolina           223.305880
North Dakota             131.415714
Ohio                     166.861697
Oklahoma                 298.233182
Oregon                   140.573790
Pennsylvania             198.487077
Rhode Island             404.070643
South Carolina           201.945476
South Dakota             109.630000
Tennessee                167.551219
Texas                    172.779742
Utah                     211.699170
Vermont                  811.760909
Virginia                 315.342500
Washington               273.994605
West Virginia            302.456000
Wisconsin                291.951000
Wyoming                 1603.136000
Name: Sales, dtype: float64

In [32]:
df.loc[df['Ship Mode']=='First Class']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
35,36,CA-2016-117590,2016-12-08,2016-12-10,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.5440,7,0.20,123.4737
36,37,CA-2016-117590,2016-12-08,2016-12-10,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.9200,5,0.60,-147.9630
44,45,CA-2016-118255,2016-03-11,2016-03-13,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,...,55122,Central,TEC-AC-10000171,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,45.9800,2,0.00,19.7714
45,46,CA-2016-118255,2016-03-11,2016-03-13,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,...,55122,Central,OFF-BI-10003291,Office Supplies,Binders,Wilson Jones Leather-Like Binders with DublLoc...,17.4600,2,0.00,8.2062
55,56,CA-2016-111682,2016-06-17,2016-06-18,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,...,12180,East,OFF-ST-10000604,Office Supplies,Storage,Home/Office Personal File Carts,208.5600,6,0.00,52.1400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9927,9928,CA-2015-159534,2015-03-20,2015-03-23,First Class,DH-13075,Dave Hallsten,Corporate,United States,New York City,...,10035,East,OFF-ST-10001172,Office Supplies,Storage,"Tennsco Lockers, Sand",83.9200,4,0.00,20.1408
9933,9934,CA-2014-166555,2014-07-11,2014-07-14,First Class,JK-15205,Jamie Kunitz,Consumer,United States,Niagara Falls,...,14304,East,TEC-PH-10004912,Technology,Phones,Cisco SPA112 2 Port Phone Adapter,164.8500,3,0.00,47.8065
9961,9962,CA-2015-168088,2015-03-19,2015-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,77041,Central,OFF-PA-10000675,Office Supplies,Paper,Xerox 1919,65.5840,2,0.20,23.7742
9962,9963,CA-2015-168088,2015-03-19,2015-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,77041,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704
9981,9982,CA-2017-163566,2017-08-03,2017-08-06,First Class,TB-21055,Ted Butterfield,Consumer,United States,Fairfield,...,45014,East,OFF-LA-10004484,Office Supplies,Labels,Avery 476,16.5200,5,0.20,5.3690

In [33]:
df.loc[df['State']=='California']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,9987,CA-2016-125794,2016-09-29,2016-10-03,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,90008,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,0.0,15.2208
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [34]:
df.loc[df['Category']=='Office Supplies']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,9983,US-2016-157728,2016-09-22,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,49505,Central,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.560,7,0.0,16.7132
9984,9985,CA-2015-100251,2015-05-17,2015-05-23,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.500,10,0.0,15.1200
9985,9986,CA-2015-100251,2015-05-17,2015-05-23,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.600,4,0.0,16.1240
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [ ]:
7